fsl = https://github.com/softlang/fsl.git

all:
	make phase1
	make phase2
	make phase3
	make phase4
	make phase5
	make phase6
	make phase7
	make phase8
	make phase9a
	make phase9b
	make phase9c
	make phase9d
	make phase9e
	make phase9f
	make phase9g
	make phase9h
	make phase9i

phase1: 
	git clone ${fsl} phase1
	cd phase1; git checkout f200bc4747e0d4ed0eb24440a18b97179e9d3885

phase2:
	git clone ${fsl} phase2
	cd phase2; git checkout ae520ca1636c6836b79d9a78bf77b78073da7317

phase3:
	git clone ${fsl} phase3
	cd phase3; git checkout 763eb9a3fff6c7ff049efe2c42661c3fe209aba8

phase4:
	git clone ${fsl} phase4
	cd phase4; git checkout 10dffd8e0d52aefe1de2249cfb2fdfd0f1d5da80

phase5:
	git clone ${fsl} phase5
	cd phase5; git checkout 4286426add865368e3a525412319897e424724b7

phase6:
	git clone ${fsl} phase6
	cd phase6; git checkout 2b31f77c76b24d542bdeecdba233f087e40b2a11

phase7:
	git clone ${fsl} phase7
	cd phase7; git checkout 01860e0f83073b1585ba2e7c0d1e380ac3f78a90

phase8:
	git clone ${fsl} phase8
	cd phase8; git checkout 1ff21fd72f411a9ed35950df964333e2ad87c86c

phase9a:
	git clone ${fsl} phase9a
	cd phase9a; git checkout 893ac5baa50b00306c602f49e9411a8ce694d01f

phase9b:
	git clone ${fsl} phase9b
	cd phase9b; git checkout 98a22f8a58cf1508befbef3d880c89ed11458b19

phase9c:
	git clone ${fsl} phase9c
	cd phase9c; git checkout 18b47af242a83cf12f8d82765b6b31c7b1f3540f

phase9d:
	git clone ${fsl} phase9d
	cd phase9d; git checkout abec42f5795f47a3efd014f9cf7c9ec70d7ae92c

phase9e:
	git clone ${fsl} phase9e
	cd phase9e; git checkout c235855c52d82b492bf52bef4addd72b8c20fd49

phase9f:
	git clone ${fsl} phase9f
	cd phase9f; git checkout f17f379a8f01cf92e0e45171340fbe6b783ce59d

phase9g:
	git clone ${fsl} phase9g
	cd phase9g; git checkout 8bf6a13b9f79f78fc764b9c43f5335acdae72a9b

phase9h:
	git clone ${fsl} phase9h
	cd phase9h; git checkout e7fe9703783420fb9fc55c3da3f53bdb37588b72

phase9i:
	git clone ${fsl} phase9i
	cd phase9i; git checkout b9183b7361540379873ab556966bf83b30fe3c67

clean:
	rm -rf phase*


