all:
	cd phase2; make
	cd phase3; make
	cd entities; make
	cd properties; make
	cd spaces; make
	cd language_concepts; make
	cd se_activities; make
	cd modules; make
	cd constraints; make
	cd issues; make
	cd references; make

